export const VOCAB = [
  {id:'v1',cat:'🌟 ESSENTIALS',en:'Hello',ru:'Привет',pr:'Privet',ex_ru:'Привет! Как дела?',ex_en:'Hello! How are you?'},
  {id:'v2',cat:'🌟 ESSENTIALS',en:'Good morning',ru:'Доброе утро',pr:'Dobroye utro',ex_ru:'Доброе утро! Как спалось?',ex_en:'Good morning! Did you sleep well?'},
  {id:'v3',cat:'🌟 ESSENTIALS',en:'Good afternoon',ru:'Добрый день',pr:'Dobryy den\'',ex_ru:'Добрый день! Рад вас видеть.',ex_en:'Good afternoon! Glad to see you.'},
  {id:'v4',cat:'🌟 ESSENTIALS',en:'Good evening',ru:'Добрый вечер',pr:'Dobryy vecher',ex_ru:'Добрый вечер! Как прошёл день?',ex_en:'Good evening! How was your day?'},
  {id:'v5',cat:'🌟 ESSENTIALS',en:'Goodbye',ru:'До свидания',pr:'Do svidaniya',ex_ru:'До свидания, увидимся завтра.',ex_en:'Goodbye, see you tomorrow.'},
  {id:'v6',cat:'🌟 ESSENTIALS',en:'See you later',ru:'Пока',pr:'Poka',ex_ru:'Пока! Созвонимся.',ex_en:'Bye! Talk later.'},
  {id:'v7',cat:'🌟 ESSENTIALS',en:'Thank you',ru:'Спасибо',pr:'Spasibo',ex_ru:'Большое спасибо за помощь.',ex_en:'Thank you very much for your help.'},
  {id:'v8',cat:'🌟 ESSENTIALS',en:'You\'re welcome',ru:'Пожалуйста',pr:'Pozhaluysta',ex_ru:'Пожалуйста, обращайся.',ex_en:'You\'re welcome, feel free.'},
  {id:'v9',cat:'🌟 ESSENTIALS',en:'Please',ru:'Пожалуйста',pr:'Pozhaluysta',ex_ru:'Дайте мне воды, пожалуйста.',ex_en:'Please give me some water.'},
  {id:'v10',cat:'🌟 ESSENTIALS',en:'Sorry / Excuse me',ru:'Извините',pr:'Izvinite',ex_ru:'Извините, я опоздал.',ex_en:'Sorry, I was late.'},
  {id:'v11',cat:'🌟 ESSENTIALS',en:'I don\'t understand',ru:'Я не понимаю',pr:'Ya ne ponimayu',ex_ru:'Извините, я не понимаю.',ex_en:'Sorry, I don\'t understand.'},
  {id:'v12',cat:'🌟 ESSENTIALS',en:'Do you speak English?',ru:'Вы говорите по-английски?',pr:'Vy govorite po-angliyski?',ex_ru:'Вы говорите по-английски?',ex_en:'Do you speak English?'},
  {id:'v13',cat:'🌟 ESSENTIALS',en:'I\'m learning Russian',ru:'Я учу русский',pr:'Ya uchu russkiy',ex_ru:'Я учу русский язык.',ex_en:'I\'m learning Russian.'},
  {id:'v14',cat:'🌟 ESSENTIALS',en:'What is your name?',ru:'Как вас зовут?',pr:'Kak vas zovut?',ex_ru:'Как вас зовут?',ex_en:'What is your name?'},
  {id:'v15',cat:'🌟 ESSENTIALS',en:'My name is...',ru:'Меня зовут...',pr:'Menya zovut...',ex_ru:'Меня зовут Иван.',ex_en:'My name is Ivan.'},
  {id:'v16',cat:'🌟 ESSENTIALS',en:'Nice to meet you',ru:'Приятно познакомиться',pr:'Priyatno poznakomit\'sya',ex_ru:'Очень приятно познакомиться.',ex_en:'Very nice to meet you.'},
  {id:'v17',cat:'🌟 ESSENTIALS',en:'How are you?',ru:'Как дела?',pr:'Kak dela?',ex_ru:'Как дела? Всё хорошо?',ex_en:'How are you? Everything good?'},
  {id:'v18',cat:'🌟 ESSENTIALS',en:'Fine / Good',ru:'Хорошо',pr:'Khorosho',ex_ru:'Всё хорошо, спасибо.',ex_en:'Everything\'s good, thanks.'},
  {id:'v19',cat:'🌟 ESSENTIALS',en:'Yes',ru:'Да',pr:'Da',ex_ru:'Да, я согласен.',ex_en:'Yes, I agree.'},
  {id:'v20',cat:'🌟 ESSENTIALS',en:'No',ru:'Нет',pr:'Net',ex_ru:'Нет, это неправильно.',ex_en:'No, that\'s wrong.'},
  {id:'v21',cat:'🍽️ FOOD',en:'water',ru:'вода',pr:'voda',ex_ru:'Дайте мне воды.',ex_en:'Give me some water.'},
  {id:'v22',cat:'🍽️ FOOD',en:'coffee',ru:'кофе',pr:'kofe',ex_ru:'Один кофе, пожалуйста.',ex_en:'One coffee, please.'},
  {id:'v23',cat:'🍽️ FOOD',en:'tea',ru:'чай',pr:'chay',ex_ru:'Хотите чаю?',ex_en:'Would you like some tea?'},
  {id:'v24',cat:'🍽️ FOOD',en:'bread',ru:'хлеб',pr:'khleb',ex_ru:'Свежий хлеб очень вкусный.',ex_en:'Fresh bread is very tasty.'},
  {id:'v25',cat:'🍽️ FOOD',en:'delicious',ru:'вкусно',pr:'vkusno',ex_ru:'Это очень вкусно!',ex_en:'This is very delicious!'},
  {id:'v26',cat:'🍽️ FOOD',en:'I\'m hungry',ru:'Я голодный',pr:'Ya golodnyy',ex_ru:'Я очень голодный сейчас.',ex_en:'I\'m very hungry right now.'},
  {id:'v27',cat:'🍽️ FOOD',en:'restaurant',ru:'ресторан',pr:'restoran',ex_ru:'Пойдём в ресторан?',ex_en:'Shall we go to the restaurant?'},
  {id:'v28',cat:'🔢 NUMBERS',en:'one',ru:'один',pr:'odin',ex_ru:'У меня один вопрос.',ex_en:'I have one question.'},
  {id:'v29',cat:'🔢 NUMBERS',en:'two',ru:'два',pr:'dva',ex_ru:'Нам нужно два билета.',ex_en:'We need two tickets.'},
  {id:'v30',cat:'🔢 NUMBERS',en:'three',ru:'три',pr:'tri',ex_ru:'Три часа дня.',ex_en:'Three o\'clock.'},
  {id:'v31',cat:'🔢 NUMBERS',en:'ten',ru:'десять',pr:'desyat\'',ex_ru:'Мне нужно десять минут.',ex_en:'I need ten minutes.'},
  {id:'v32',cat:'🔢 NUMBERS',en:'hundred',ru:'сто',pr:'sto',ex_ru:'Это стоит сто рублей.',ex_en:'It costs one hundred rubles.'},
  {id:'v33',cat:'⏰ TIME',en:'today',ru:'сегодня',pr:'segodnya',ex_ru:'Сегодня хорошая погода.',ex_en:'Today the weather is nice.'},
  {id:'v34',cat:'⏰ TIME',en:'tomorrow',ru:'завтра',pr:'zavtra',ex_ru:'Увидимся завтра.',ex_en:'See you tomorrow.'},
  {id:'v35',cat:'⏰ TIME',en:'yesterday',ru:'вчера',pr:'vchera',ex_ru:'Вчера был прекрасный день.',ex_en:'Yesterday was a wonderful day.'},
  {id:'v36',cat:'⏰ TIME',en:'now',ru:'сейчас',pr:'seychas',ex_ru:'Я занят сейчас.',ex_en:'I\'m busy right now.'},
  {id:'v37',cat:'⏰ TIME',en:'morning',ru:'утро',pr:'utro',ex_ru:'Я встаю рано утром.',ex_en:'I wake up early in the morning.'},
  {id:'v38',cat:'⏰ TIME',en:'evening',ru:'вечер',pr:'vecher',ex_ru:'Вечером идём в кино.',ex_en:'In the evening we\'re going to the movies.'},
  {id:'v39',cat:'⏰ TIME',en:'night / Good night',ru:'Спокойной ночи',pr:'Spokoynoy nochi',ex_ru:'Спокойной ночи, до завтра!',ex_en:'Good night, see you tomorrow!'},
  {id:'v40',cat:'⏰ TIME',en:'week',ru:'неделя',pr:'nedelya',ex_ru:'На этой неделе я занят.',ex_en:'I\'m busy this week.'},
  {id:'v41',cat:'💼 WORK',en:'work',ru:'работа',pr:'rabota',ex_ru:'Я иду на работу.',ex_en:'I\'m going to work.'},
  {id:'v42',cat:'💼 WORK',en:'money',ru:'деньги',pr:'den\'gi',ex_ru:'У меня нет денег.',ex_en:'I don\'t have money.'},
  {id:'v43',cat:'💼 WORK',en:'price',ru:'цена',pr:'tsena',ex_ru:'Какая цена?',ex_en:'What\'s the price?'},
  {id:'v44',cat:'💼 WORK',en:'expensive',ru:'дорого',pr:'dorogo',ex_ru:'Это слишком дорого.',ex_en:'That\'s too expensive.'},
  {id:'v45',cat:'💼 WORK',en:'cheap',ru:'дёшево',pr:'dyoshevo',ex_ru:'Это очень дёшево.',ex_en:'That\'s very cheap.'},
  {id:'v46',cat:'🏠 HOME',en:'home / house',ru:'дом',pr:'dom',ex_ru:'Я иду домой.',ex_en:'I\'m going home.'},
  {id:'v47',cat:'🏠 HOME',en:'apartment',ru:'квартира',pr:'kvartira',ex_ru:'Я живу в квартире.',ex_en:'I live in an apartment.'},
  {id:'v48',cat:'🏠 HOME',en:'room',ru:'комната',pr:'komnata',ex_ru:'Моя комната маленькая.',ex_en:'My room is small.'},
  {id:'v49',cat:'👨‍👩‍👧 FAMILY',en:'mother',ru:'мама',pr:'mama',ex_ru:'Моя мама добрая.',ex_en:'My mother is kind.'},
  {id:'v50',cat:'👨‍👩‍👧 FAMILY',en:'father',ru:'папа',pr:'papa',ex_ru:'Мой папа работает врачом.',ex_en:'My father works as a doctor.'},
  {id:'v51',cat:'👨‍👩‍👧 FAMILY',en:'friend',ru:'друг',pr:'drug',ex_ru:'Это мой лучший друг.',ex_en:'This is my best friend.'},
  {id:'v52',cat:'👨‍👩‍👧 FAMILY',en:'brother',ru:'брат',pr:'brat',ex_ru:'У меня есть брат.',ex_en:'I have a brother.'},
  {id:'v53',cat:'👨‍👩‍👧 FAMILY',en:'sister',ru:'сестра',pr:'sestra',ex_ru:'Моя сестра учится в школе.',ex_en:'My sister studies in school.'},
  {id:'v54',cat:'🌍 TRAVEL',en:'where',ru:'где',pr:'gde',ex_ru:'Где находится метро?',ex_en:'Where is the metro?'},
  {id:'v55',cat:'🌍 TRAVEL',en:'how much',ru:'сколько',pr:'skol\'ko',ex_ru:'Сколько стоит?',ex_en:'How much does it cost?'},
  {id:'v56',cat:'🌍 TRAVEL',en:'hotel',ru:'гостиница',pr:'gostinitsa',ex_ru:'Я живу в гостинице.',ex_en:'I\'m staying in a hotel.'},
  {id:'v57',cat:'🌍 TRAVEL',en:'help me please',ru:'Помогите мне',pr:'Pomogite mne',ex_ru:'Помогите мне, пожалуйста.',ex_en:'Please help me.'},
  {id:'v58',cat:'🌍 TRAVEL',en:'I\'m lost',ru:'Я заблудился',pr:'Ya zabludilsya',ex_ru:'Я заблудился. Помогите!',ex_en:'I\'m lost. Help!'},
  {id:'v59',cat:'🏥 HEALTH',en:'doctor',ru:'врач',pr:'vrach',ex_ru:'Мне нужен врач.',ex_en:'I need a doctor.'},
  {id:'v60',cat:'🏥 HEALTH',en:'I feel sick',ru:'Мне плохо',pr:'Mne plokho',ex_ru:'Мне плохо, нужна помощь.',ex_en:'I feel sick, I need help.'},
  {id:'v61',cat:'🏥 HEALTH',en:'pain',ru:'боль',pr:'bol\'',ex_ru:'У меня сильная боль.',ex_en:'I have strong pain.'},
  {id:'v62',cat:'🏥 HEALTH',en:'call an ambulance',ru:'Вызовите скорую',pr:'Vyzovite skoruyu',ex_ru:'Пожалуйста, вызовите скорую.',ex_en:'Please call an ambulance.'},
  {id:'v63',cat:'💬 PHRASES',en:'I think',ru:'Я думаю',pr:'Ya dumayu',ex_ru:'Я думаю, это хорошая идея.',ex_en:'I think that\'s a good idea.'},
  {id:'v64',cat:'💬 PHRASES',en:'I want',ru:'Я хочу',pr:'Ya khochu',ex_ru:'Я хочу научиться.',ex_en:'I want to learn.'},
  {id:'v65',cat:'💬 PHRASES',en:'maybe',ru:'может быть',pr:'mozhet byt\'',ex_ru:'Может быть, завтра.',ex_en:'Maybe tomorrow.'},
  {id:'v66',cat:'💬 PHRASES',en:'of course',ru:'конечно',pr:'konechno',ex_ru:'Конечно, я помогу!',ex_en:'Of course, I\'ll help!'},
  {id:'x1',cat:'🏙️ CITY',en:'city center',ru:'центр города',pr:'tsentr goroda',ex_ru:'Мы идём в центр города.',ex_en:'We\'re going to the city center.'},
  {id:'x2',cat:'🏙️ CITY',en:'pedestrian street',ru:'пешеходная улица',pr:'peshekhodnaya ulitsa',ex_ru:'Здесь красивая пешеходная улица.',ex_en:'There\'s a beautiful pedestrian street here.'},
  {id:'x3',cat:'🏙️ CITY',en:'crosswalk',ru:'пешеходный переход',pr:'peshekhodnyy perekhod',ex_ru:'Переходи только на пешеходном переходе.',ex_en:'Cross only at the crosswalk.'},
  {id:'x4',cat:'🏙️ CITY',en:'traffic light',ru:'светофор',pr:'svetofor',ex_ru:'Стой у светофора.',ex_en:'Stop at the traffic light.'},
  {id:'x5',cat:'🏙️ CITY',en:'sidewalk',ru:'тротуар',pr:'trotuaar',ex_ru:'Иди по тротуару.',ex_en:'Walk on the sidewalk.'},
  {id:'x6',cat:'🏙️ CITY',en:'square',ru:'площадь',pr:'ploshchad\'',ex_ru:'Встретимся на площади.',ex_en:'Let\'s meet at the square.'},
  {id:'x7',cat:'🏙️ CITY',en:'museum',ru:'музей',pr:'muzey',ex_ru:'Я хочу пойти в музей.',ex_en:'I want to go to the museum.'},
  {id:'x8',cat:'🏙️ CITY',en:'post office',ru:'почта',pr:'pochta',ex_ru:'Где ближайшая почта?',ex_en:'Where\'s the nearest post office?'},
  {id:'x9',cat:'🏙️ CITY',en:'bank',ru:'банк',pr:'bank',ex_ru:'Мне нужно в банк.',ex_en:'I need to go to the bank.'},
  {id:'x10',cat:'🏙️ CITY',en:'ATM',ru:'банкомат',pr:'bankomat',ex_ru:'Где есть банкомат?',ex_en:'Where is there an ATM?'},
  {id:'x11',cat:'🏙️ CITY',en:'pharmacy',ru:'аптека',pr:'apteka',ex_ru:'Аптека работает круглосуточно.',ex_en:'The pharmacy is open 24/7.'},
  {id:'x12',cat:'🏙️ CITY',en:'supermarket',ru:'супермаркет',pr:'supermarket',ex_ru:'Я иду в супермаркет.',ex_en:'I\'m going to the supermarket.'},
  {id:'x13',cat:'🏙️ CITY',en:'bookstore',ru:'книжный магазин',pr:'knizhnyy magazin',ex_ru:'В книжном магазине большой выбор.',ex_en:'The bookstore has a big selection.'},
  {id:'x14',cat:'🏙️ CITY',en:'café',ru:'кафе',pr:'kafe',ex_ru:'Давай зайдём в кафе.',ex_en:'Let\'s stop by the café.'},
  {id:'x15',cat:'🏙️ CITY',en:'cinema',ru:'кинотеатр',pr:'kinoteatr',ex_ru:'Что идёт в кинотеатре?',ex_en:'What\'s playing at the cinema?'},
  {id:'x16',cat:'🏙️ CITY',en:'bridge',ru:'мост',pr:'most',ex_ru:'Мы перешли через мост.',ex_en:'We crossed the bridge.'},
  {id:'x17',cat:'🏙️ CITY',en:'embankment',ru:'набережная',pr:'naberezhnaya',ex_ru:'Гуляем по набережной.',ex_en:'We\'re walking along the embankment.'},
  {id:'x18',cat:'🏙️ CITY',en:'neighborhood',ru:'район',pr:'rayon',ex_ru:'Я живу в хорошем районе.',ex_en:'I live in a good neighborhood.'},
  {id:'x19',cat:'🏙️ CITY',en:'downtown',ru:'в центре',pr:'v tsentre',ex_ru:'Ты работаешь в центре?',ex_en:'Do you work downtown?'},
  {id:'x20',cat:'🏙️ CITY',en:'outskirts',ru:'окраина',pr:'okraina',ex_ru:'Он живёт на окраине города.',ex_en:'He lives on the outskirts.'},
  {id:'x21',cat:'🏙️ CITY',en:'traffic jam',ru:'пробка',pr:'probka',ex_ru:'Сегодня большие пробки.',ex_en:'There are big traffic jams today.'},
  {id:'x22',cat:'🏙️ CITY',en:'parking',ru:'парковка',pr:'parkovka',ex_ru:'Где здесь парковка?',ex_en:'Where is the parking here?'},
  {id:'x23',cat:'🏙️ CITY',en:'street',ru:'улица',pr:'ulitsa',ex_ru:'Как называется эта улица?',ex_en:'What is this street called?'},
  {id:'x24',cat:'🏙️ CITY',en:'building',ru:'здание',pr:'zdaniye',ex_ru:'Какое красивое здание!',ex_en:'What a beautiful building!'},
  {id:'x25',cat:'🏙️ CITY',en:'fountain',ru:'фонтан',pr:'fontan',ex_ru:'Фонтан работает летом.',ex_en:'The fountain runs in summer.'},
  {id:'x26',cat:'🏙️ CITY',en:'library',ru:'библиотека',pr:'biblioteka',ex_ru:'В библиотеке тихо.',ex_en:'It\'s quiet in the library.'},
  {id:'x27',cat:'🏙️ CITY',en:'theater',ru:'театр',pr:'teatr',ex_ru:'Спектакль в театре начинается в 7.',ex_en:'The show at the theater starts at 7.'},
  {id:'x28',cat:'🏙️ CITY',en:'stadium',ru:'стадион',pr:'stadion',ex_ru:'Стадион заполнен до отказа.',ex_en:'The stadium is packed.'},
  {id:'x29',cat:'🏙️ CITY',en:'river',ru:'река',pr:'reka',ex_ru:'Москва-река очень широкая.',ex_en:'The Moscow River is very wide.'},
  {id:'x30',cat:'🏙️ CITY',en:'apartment block',ru:'многоквартирный дом',pr:'mnogokvartirnyy dom',ex_ru:'Я живу в многоквартирном доме.',ex_en:'I live in an apartment block.'},
  {id:'x31',cat:'🏙️ CITY',en:'construction',ru:'стройка',pr:'stroyka',ex_ru:'Здесь идёт стройка.',ex_en:'There\'s construction here.'},
  {id:'x32',cat:'🏙️ CITY',en:'city park',ru:'городской парк',pr:'gorodskoy park',ex_ru:'Пойдём погуляем в городском парке.',ex_en:'Let\'s go for a walk in the city park.'},
  {id:'x33',cat:'🏙️ CITY',en:'public transport',ru:'общественный транспорт',pr:'obshchestvennyy transport',ex_ru:'Я езжу на общественном транспорте.',ex_en:'I use public transport.'},
  {id:'x34',cat:'🏙️ CITY',en:'city hall',ru:'мэрия',pr:'meriya',ex_ru:'Мэрия находится в центре.',ex_en:'City hall is in the center.'},
  {id:'x35',cat:'🏙️ CITY',en:'shopping mall',ru:'торговый центр',pr:'torgovyy tsentr',ex_ru:'Встретимся у торгового центра.',ex_en:'Let\'s meet at the shopping mall.'},
  {id:'x36',cat:'🎭 SLANG',en:'cool',ru:'круто',pr:'kruto',ex_ru:'Это очень круто!',ex_en:'That\'s really cool!'},
  {id:'x37',cat:'🎭 SLANG',en:'awesome',ru:'классно',pr:'klassno',ex_ru:'Классно провели время!',ex_en:'We had an awesome time!'},
  {id:'x38',cat:'🎭 SLANG',en:'dude / man',ru:'чувак',pr:'chuvak',ex_ru:'Чувак, ты видел это?',ex_en:'Dude, did you see that?'},
  {id:'x39',cat:'🎭 SLANG',en:'no problem / chill',ru:'всё норм',pr:'vsyo norm',ex_ru:'Всё норм, не парься.',ex_en:'All good, don\'t stress.'},
  {id:'x40',cat:'🎭 SLANG',en:'don\'t stress',ru:'не парься',pr:'ne par\'sya',ex_ru:'Не парься, всё будет хорошо.',ex_en:'Don\'t stress, everything will be fine.'},
  {id:'x41',cat:'🎭 SLANG',en:'bro',ru:'братан',pr:'bratan',ex_ru:'Братан, помоги мне.',ex_en:'Bro, help me out.'},
  {id:'x42',cat:'🎭 SLANG',en:'for sure',ru:'однозначно',pr:'odnoznachno',ex_ru:'Однозначно пойдём туда!',ex_en:'Absolutely we\'ll go there!'},
  {id:'x43',cat:'🎭 SLANG',en:'nonsense',ru:'ерунда',pr:'yerunda',ex_ru:'Это полная ерунда.',ex_en:'That\'s total nonsense.'},
  {id:'x44',cat:'🎭 SLANG',en:'got it',ru:'понял',pr:'ponyal',ex_ru:'Понял, сделаю.',ex_en:'Got it, I\'ll do it.'},
  {id:'x45',cat:'🎭 SLANG',en:'for real?',ru:'серьёзно?',pr:'seryozno?',ex_ru:'Серьёзно? Не верю!',ex_en:'For real? I don\'t believe it!'},
  {id:'x46',cat:'🎭 SLANG',en:'whatever',ru:'ладно',pr:'ladno',ex_ru:'Ладно, как хочешь.',ex_en:'Whatever, as you wish.'},
  {id:'x47',cat:'🎭 SLANG',en:'to chill / hang',ru:'тусить',pr:'tusit\'',ex_ru:'Мы просто тусим.',ex_en:'We\'re just chilling.'},
  {id:'x48',cat:'🎭 SLANG',en:'hangout / party',ru:'тусовка',pr:'tusovka',ex_ru:'Будет крутая тусовка.',ex_en:'There\'ll be a cool hangout.'},
  {id:'x49',cat:'🎭 SLANG',en:'lame / garbage',ru:'отстой',pr:'otstoy',ex_ru:'Этот фильм — полный отстой.',ex_en:'This movie is total garbage.'},
  {id:'x50',cat:'🎭 SLANG',en:'fire / awesome',ru:'огонь',pr:'ogon\'',ex_ru:'Музыка просто огонь!',ex_en:'The music is fire!'},
  {id:'x51',cat:'🎭 SLANG',en:'to mess up',ru:'облажаться',pr:'oblazhat\'sya',ex_ru:'Я облажался на экзамене.',ex_en:'I messed up the exam.'},
  {id:'x52',cat:'🎭 SLANG',en:'totally broke',ru:'без копейки',pr:'bez kopeyki',ex_ru:'Я сейчас без копейки.',ex_en:'I\'m totally broke right now.'},
  {id:'x53',cat:'🎭 SLANG',en:'to goof off',ru:'балду гонять',pr:'baldu gonyat\'',ex_ru:'Хватит балду гонять!',ex_en:'Stop goofing off!'},
  {id:'x54',cat:'🎭 SLANG',en:'to nag',ru:'приставать',pr:'pristavat\'',ex_ru:'Не приставай ко мне.',ex_en:'Stop nagging me.'},
  {id:'x55',cat:'🎭 SLANG',en:'drained / wiped',ru:'вымотался',pr:'vymotalsya',ex_ru:'Я полностью вымотался.',ex_en:'I\'m completely drained.'},
  {id:'x56',cat:'🎭 SLANG',en:'to joke around',ru:'прикалываться',pr:'prikalyvat\'sya',ex_ru:'Ты прикалываешься?',ex_en:'Are you kidding?'},
  {id:'x57',cat:'🎭 SLANG',en:'joke',ru:'прикол',pr:'prikol',ex_ru:'Это был прикол!',ex_en:'That was a joke!'},
  {id:'x58',cat:'🎭 SLANG',en:'to screw up',ru:'напортачить',pr:'naportachit\'',ex_ru:'Ты опять напортачил!',ex_en:'You screwed up again!'},
  {id:'x59',cat:'🎭 SLANG',en:'to show off',ru:'понтоваться',pr:'pontovat\'sya',ex_ru:'Хватит понтоваться.',ex_en:'Stop showing off.'},
  {id:'x60',cat:'🎭 SLANG',en:'not my problem',ru:'не моя проблема',pr:'ne moya problema',ex_ru:'Это не моя проблема.',ex_en:'That\'s not my problem.'},
  {id:'x61',cat:'🎭 SLANG',en:'type of / like',ru:'типа',pr:'tipa',ex_ru:'Это типа сложно.',ex_en:'It\'s like, complicated.'},
  {id:'x62',cat:'🎭 SLANG',en:'kind of',ru:'как бы',pr:'kak by',ex_ru:'Как бы да, но не совсем.',ex_en:'Kind of yes, but not exactly.'},
  {id:'x63',cat:'🎭 SLANG',en:'epic fail',ru:'эпик фейл',pr:'epik feyl',ex_ru:'Это был эпик фейл.',ex_en:'That was an epic fail.'},
  {id:'x64',cat:'🎭 SLANG',en:'so-so / meh',ru:'так себе',pr:'tak sebe',ex_ru:'Фильм так себе.',ex_en:'The film was meh.'},
  {id:'x65',cat:'🎭 SLANG',en:'to vanish / ghost',ru:'слинять',pr:'slinat\'',ex_ru:'Он просто слинял.',ex_en:'He just vanished.'},
  {id:'x66',cat:'🎭 SLANG',en:'in a rush',ru:'на бегу',pr:'na begu',ex_ru:'Я сейчас на бегу.',ex_en:'I\'m on the run right now.'},
  {id:'x67',cat:'🎭 SLANG',en:'it\'s lit / happening',ru:'движ',pr:'dvizh',ex_ru:'Сегодня будет движ!',ex_en:'Tonight is gonna be lit!'},
  {id:'x68',cat:'🎭 SLANG',en:'to chill at home',ru:'сидеть дома',pr:'sidet\' doma',ex_ru:'Я сегодня сижу дома.',ex_en:'I\'m chilling at home today.'},
  {id:'x69',cat:'🎭 SLANG',en:'homie / my people',ru:'свои',pr:'svoi',ex_ru:'Здесь только свои.',ex_en:'It\'s only our people here.'},
  {id:'x70',cat:'🎭 SLANG',en:'vibe check',ru:'проверка атмосферы',pr:'proverka atmosfery',ex_ru:'Вайб здесь — огонь.',ex_en:'The vibe here is fire.'},
  {id:'x71',cat:'🚗 TRANSPORT',en:'subway / metro',ru:'метро',pr:'metro',ex_ru:'Поедем на метро.',ex_en:'Let\'s take the metro.'},
  {id:'x72',cat:'🚗 TRANSPORT',en:'metro station',ru:'станция метро',pr:'stantsiya metro',ex_ru:'Какая ближайшая станция метро?',ex_en:'What\'s the nearest metro station?'},
  {id:'x73',cat:'🚗 TRANSPORT',en:'bus',ru:'автобус',pr:'avtobus',ex_ru:'Автобус опаздывает.',ex_en:'The bus is late.'},
  {id:'x74',cat:'🚗 TRANSPORT',en:'bus stop',ru:'остановка',pr:'ostanovka',ex_ru:'Подожди на остановке.',ex_en:'Wait at the bus stop.'},
  {id:'x75',cat:'🚗 TRANSPORT',en:'tram',ru:'трамвай',pr:'tramvay',ex_ru:'Я люблю ездить на трамвае.',ex_en:'I like riding the tram.'},
  {id:'x76',cat:'🚗 TRANSPORT',en:'taxi',ru:'такси',pr:'taksi',ex_ru:'Вызови такси.',ex_en:'Call a taxi.'},
  {id:'x77',cat:'🚗 TRANSPORT',en:'train',ru:'поезд',pr:'poyezd',ex_ru:'Поезд отправляется в 10.',ex_en:'The train departs at 10.'},
  {id:'x78',cat:'🚗 TRANSPORT',en:'train station',ru:'вокзал',pr:'vokzal',ex_ru:'Где находится вокзал?',ex_en:'Where is the train station?'},
  {id:'x79',cat:'🚗 TRANSPORT',en:'airport',ru:'аэропорт',pr:'aeroport',ex_ru:'Меня везут в аэропорт.',ex_en:'I\'m being taken to the airport.'},
  {id:'x80',cat:'🚗 TRANSPORT',en:'flight',ru:'рейс',pr:'reys',ex_ru:'Мой рейс задержан.',ex_en:'My flight is delayed.'},
  {id:'x81',cat:'🚗 TRANSPORT',en:'ticket',ru:'билет',pr:'bilet',ex_ru:'Мне нужен билет на поезд.',ex_en:'I need a train ticket.'},
  {id:'x82',cat:'🚗 TRANSPORT',en:'round trip',ru:'туда и обратно',pr:'tuda i obratno',ex_ru:'Дайте два билета туда и обратно.',ex_en:'Give me two round trip tickets.'},
  {id:'x83',cat:'🚗 TRANSPORT',en:'one way',ru:'в одну сторону',pr:'v odnu storonu',ex_ru:'Билет в одну сторону, пожалуйста.',ex_en:'One way ticket, please.'},
  {id:'x84',cat:'🚗 TRANSPORT',en:'departure',ru:'отправление',pr:'otpravleniye',ex_ru:'Когда отправление?',ex_en:'When is the departure?'},
  {id:'x85',cat:'🚗 TRANSPORT',en:'arrival',ru:'прибытие',pr:'pribytiye',ex_ru:'Время прибытия — 14:30.',ex_en:'Arrival time is 14:30.'},
  {id:'x86',cat:'🚗 TRANSPORT',en:'platform',ru:'платформа',pr:'platforma',ex_ru:'Поезд на платформе 3.',ex_en:'The train is on platform 3.'},
  {id:'x87',cat:'🚗 TRANSPORT',en:'to transfer',ru:'делать пересадку',pr:'delat\' peresadku',ex_ru:'Нужно делать пересадку?',ex_en:'Do I need to transfer?'},
  {id:'x88',cat:'🚗 TRANSPORT',en:'car',ru:'машина',pr:'mashina',ex_ru:'У меня нет машины.',ex_en:'I don\'t have a car.'},
  {id:'x89',cat:'🚗 TRANSPORT',en:'to drive',ru:'водить машину',pr:'vodit\' mashinu',ex_ru:'Ты умеешь водить?',ex_en:'Do you know how to drive?'},
  {id:'x90',cat:'🚗 TRANSPORT',en:'driver\'s license',ru:'водительские права',pr:'voditel\'skie prava',ex_ru:'Покажите права.',ex_en:'Show your license.'},
  {id:'x91',cat:'🚗 TRANSPORT',en:'gas station',ru:'заправка',pr:'zapravka',ex_ru:'Мне нужна заправка.',ex_en:'I need a gas station.'},
  {id:'x92',cat:'🚗 TRANSPORT',en:'traffic',ru:'движение',pr:'dvizheniye',ex_ru:'Движение на дороге плотное.',ex_en:'Traffic on the road is heavy.'},
  {id:'x93',cat:'🚗 TRANSPORT',en:'road',ru:'дорога',pr:'doroga',ex_ru:'Дорога мокрая.',ex_en:'The road is wet.'},
  {id:'x94',cat:'🚗 TRANSPORT',en:'highway',ru:'шоссе',pr:'shosse',ex_ru:'Едем по шоссе.',ex_en:'We\'re driving on the highway.'},
  {id:'x95',cat:'🚗 TRANSPORT',en:'turn',ru:'поворот',pr:'povorot',ex_ru:'На следующем повороте — направо.',ex_en:'At the next turn — turn right.'},
  {id:'x96',cat:'🚗 TRANSPORT',en:'bicycle',ru:'велосипед',pr:'velosiped',ex_ru:'Я езжу на велосипеде.',ex_en:'I ride a bicycle.'},
  {id:'x97',cat:'🚗 TRANSPORT',en:'scooter',ru:'самокат',pr:'samokat',ex_ru:'Возьми самокат напрокат.',ex_en:'Rent a scooter.'},
  {id:'x98',cat:'🚗 TRANSPORT',en:'stuck in traffic',ru:'стоять в пробке',pr:'stoyat\' v probke',ex_ru:'Мы стоим в пробке час.',ex_en:'We\'ve been stuck in traffic for an hour.'},
  {id:'x99',cat:'🚗 TRANSPORT',en:'luggage',ru:'багаж',pr:'bagazh',ex_ru:'Где получить багаж?',ex_en:'Where do I pick up luggage?'},
  {id:'x100',cat:'🚗 TRANSPORT',en:'fare / cost',ru:'стоимость проезда',pr:'stoimost\' proyezda',ex_ru:'Какова стоимость проезда?',ex_en:'What is the fare?'},
  {id:'x101',cat:'💕 ROMANCE',en:'I like you',ru:'Ты мне нравишься',pr:'Ty mne nravish\'sya',ex_ru:'Ты мне очень нравишься.',ex_en:'I really like you.'},
  {id:'x102',cat:'💕 ROMANCE',en:'I love you',ru:'Я тебя люблю',pr:'Ya tebya lyublyu',ex_ru:'Я тебя так люблю.',ex_en:'I love you so much.'},
  {id:'x103',cat:'💕 ROMANCE',en:'You are beautiful',ru:'Ты красивая',pr:'Ty krasivaya',ex_ru:'Ты такая красивая!',ex_en:'You are so beautiful.'},
  {id:'x104',cat:'💕 ROMANCE',en:'You are handsome',ru:'Ты красивый',pr:'Ty krasivyy',ex_ru:'Ты очень красивый.',ex_en:'You are very handsome.'},
  {id:'x105',cat:'💕 ROMANCE',en:'date',ru:'свидание',pr:'svidaniye',ex_ru:'Наше свидание прошло отлично.',ex_en:'Our date went great.'},
  {id:'x106',cat:'💕 ROMANCE',en:'kiss',ru:'поцелуй',pr:'potseluy',ex_ru:'Он её поцеловал нежно.',ex_en:'He kissed her tenderly.'},
  {id:'x107',cat:'💕 ROMANCE',en:'hug me',ru:'обними меня',pr:'obnimi menya',ex_ru:'Обними меня крепче.',ex_en:'Hug me tighter.'},
  {id:'x108',cat:'💕 ROMANCE',en:'relationship',ru:'отношения',pr:'otnosheniya',ex_ru:'У нас серьёзные отношения.',ex_en:'We have a serious relationship.'},
  {id:'x109',cat:'💕 ROMANCE',en:'boyfriend',ru:'парень',pr:'paren\'',ex_ru:'Это мой парень.',ex_en:'This is my boyfriend.'},
  {id:'x110',cat:'💕 ROMANCE',en:'girlfriend',ru:'девушка',pr:'devushka',ex_ru:'Это моя девушка.',ex_en:'This is my girlfriend.'},
  {id:'x111',cat:'💕 ROMANCE',en:'husband',ru:'муж',pr:'muzh',ex_ru:'Мой муж очень добрый.',ex_en:'My husband is very kind.'},
  {id:'x112',cat:'💕 ROMANCE',en:'wife',ru:'жена',pr:'zhena',ex_ru:'Его жена — врач.',ex_en:'His wife is a doctor.'},
  {id:'x113',cat:'💕 ROMANCE',en:'I miss you',ru:'Я скучаю по тебе',pr:'Ya skuchayu po tebe',ex_ru:'Я очень скучаю по тебе.',ex_en:'I miss you so much.'},
  {id:'x114',cat:'💕 ROMANCE',en:'I think about you',ru:'Я думаю о тебе',pr:'Ya dumayu o tebe',ex_ru:'Я всё время думаю о тебе.',ex_en:'I think about you all the time.'},
  {id:'x115',cat:'💕 ROMANCE',en:'Will you marry me?',ru:'Ты выйдешь за меня замуж?',pr:'Ty vyydesh\' za menya zamuzh?',ex_ru:'Ты выйдешь за меня замуж?',ex_en:'Will you marry me?'},
  {id:'x116',cat:'💕 ROMANCE',en:'wedding',ru:'свадьба',pr:'svad\'ba',ex_ru:'Свадьба будет летом.',ex_en:'The wedding will be in summer.'},
  {id:'x117',cat:'💕 ROMANCE',en:'forever',ru:'навсегда',pr:'navsegda',ex_ru:'Я с тобой навсегда.',ex_en:'I\'m with you forever.'},
  {id:'x118',cat:'💕 ROMANCE',en:'together',ru:'вместе',pr:'vmeste',ex_ru:'Мы вместе уже год.',ex_en:'We\'ve been together for a year.'},
  {id:'x119',cat:'💕 ROMANCE',en:'darling',ru:'дорогой / дорогая',pr:'dorogoy / dorogaya',ex_ru:'Привет, дорогая!',ex_en:'Hello, darling!'},
  {id:'x120',cat:'💕 ROMANCE',en:'to fall in love',ru:'влюбиться',pr:'vlyubit\'sya',ex_ru:'Я влюбился с первого взгляда.',ex_en:'I fell in love at first sight.'},
  {id:'x121',cat:'🌦️ WEATHER',en:'weather',ru:'погода',pr:'pogoda',ex_ru:'Какая погода сегодня?',ex_en:'What\'s the weather like today?'},
  {id:'x122',cat:'🌦️ WEATHER',en:'forecast',ru:'прогноз погоды',pr:'prognoz pogody',ex_ru:'Прогноз погоды на завтра плохой.',ex_en:'Tomorrow\'s weather forecast is bad.'},
  {id:'x123',cat:'🌦️ WEATHER',en:'sunny',ru:'солнечно',pr:'solnechno',ex_ru:'Сегодня солнечно и тепло.',ex_en:'It\'s sunny and warm today.'},
  {id:'x124',cat:'🌦️ WEATHER',en:'cloudy',ru:'облачно',pr:'oblachno',ex_ru:'Сегодня облачно.',ex_en:'It\'s cloudy today.'},
  {id:'x125',cat:'🌦️ WEATHER',en:'rainy',ru:'дождливо',pr:'dozhdlivo',ex_ru:'Сегодня дождливо.',ex_en:'It\'s rainy today.'},
  {id:'x126',cat:'🌦️ WEATHER',en:'snowy',ru:'снежно',pr:'snezhno',ex_ru:'На улице снежно.',ex_en:'It\'s snowy outside.'},
  {id:'x127',cat:'🌦️ WEATHER',en:'windy',ru:'ветрено',pr:'vetreno',ex_ru:'Сегодня очень ветрено.',ex_en:'It\'s very windy today.'},
  {id:'x128',cat:'🌦️ WEATHER',en:'cold',ru:'холодно',pr:'kholodno',ex_ru:'На улице очень холодно.',ex_en:'It\'s very cold outside.'},
  {id:'x129',cat:'🌦️ WEATHER',en:'hot',ru:'жарко',pr:'zharko',ex_ru:'Сегодня жарко.',ex_en:'It\'s hot today.'},
  {id:'x130',cat:'🌦️ WEATHER',en:'it\'s raining',ru:'идёт дождь',pr:'idyot dozhd\'',ex_ru:'Идёт дождь.',ex_en:'It\'s raining.'},
  {id:'x131',cat:'🌦️ WEATHER',en:'it\'s snowing',ru:'идёт снег',pr:'idyot sneg',ex_ru:'Идёт снег.',ex_en:'It\'s snowing.'},
  {id:'x132',cat:'🌦️ WEATHER',en:'fog',ru:'туман',pr:'tuman',ex_ru:'На дороге туман.',ex_en:'There\'s fog on the road.'},
  {id:'x133',cat:'🌦️ WEATHER',en:'storm',ru:'гроза',pr:'groza',ex_ru:'Надвигается гроза.',ex_en:'A storm is approaching.'},
  {id:'x134',cat:'🌦️ WEATHER',en:'thunder',ru:'гром',pr:'grom',ex_ru:'Слышишь гром?',ex_en:'Do you hear the thunder?'},
  {id:'x135',cat:'🌦️ WEATHER',en:'rainbow',ru:'радуга',pr:'raduga',ex_ru:'Смотри — радуга!',ex_en:'Look — a rainbow!'},
  {id:'x136',cat:'🌦️ WEATHER',en:'umbrella',ru:'зонт',pr:'zont',ex_ru:'Возьми зонт.',ex_en:'Take an umbrella.'},
  {id:'x137',cat:'🌦️ WEATHER',en:'frost',ru:'мороз',pr:'moroz',ex_ru:'Сегодня сильный мороз.',ex_en:'There\'s heavy frost today.'},
  {id:'x138',cat:'🌦️ WEATHER',en:'blizzard',ru:'метель',pr:'metel\'',ex_ru:'На улице сильная метель.',ex_en:'There\'s a blizzard outside.'},
  {id:'x139',cat:'🌦️ WEATHER',en:'heatwave',ru:'жара',pr:'zhara',ex_ru:'Эта жара невыносима.',ex_en:'This heat is unbearable.'},
  {id:'x140',cat:'🌦️ WEATHER',en:'season',ru:'время года',pr:'vremya goda',ex_ru:'Какое твоё любимое время года?',ex_en:'What\'s your favorite season?'},
  {id:'x141',cat:'🦁 ANIMALS',en:'dog',ru:'собака',pr:'sobaka',ex_ru:'У меня есть собака.',ex_en:'I have a dog.'},
  {id:'x142',cat:'🦁 ANIMALS',en:'cat',ru:'кошка',pr:'koshka',ex_ru:'Кошка спит на диване.',ex_en:'The cat is sleeping on the couch.'},
  {id:'x143',cat:'🦁 ANIMALS',en:'horse',ru:'лошадь',pr:'loshad\'',ex_ru:'Лошадь — красивое животное.',ex_en:'The horse is a beautiful animal.'},
  {id:'x144',cat:'🦁 ANIMALS',en:'bear',ru:'медведь',pr:'medved\'',ex_ru:'В России много медведей.',ex_en:'There are many bears in Russia.'},
  {id:'x145',cat:'🦁 ANIMALS',en:'wolf',ru:'волк',pr:'volk',ex_ru:'Волк воет на луну.',ex_en:'The wolf howls at the moon.'},
  {id:'x146',cat:'🦁 ANIMALS',en:'fox',ru:'лиса',pr:'lisa',ex_ru:'Лиса очень хитрая.',ex_en:'The fox is very cunning.'},
  {id:'x147',cat:'🦁 ANIMALS',en:'eagle',ru:'орёл',pr:'oryol',ex_ru:'Орёл — символ силы.',ex_en:'The eagle is a symbol of strength.'},
  {id:'x148',cat:'🦁 ANIMALS',en:'lion',ru:'лев',pr:'lev',ex_ru:'Лев — царь зверей.',ex_en:'The lion is king of the beasts.'},
  {id:'x149',cat:'🦁 ANIMALS',en:'tiger',ru:'тигр',pr:'tigr',ex_ru:'Амурский тигр живёт в России.',ex_en:'The Amur tiger lives in Russia.'},
  {id:'x150',cat:'🦁 ANIMALS',en:'butterfly',ru:'бабочка',pr:'babochka',ex_ru:'Бабочка сидит на цветке.',ex_en:'The butterfly is on the flower.'},
  {id:'x151',cat:'🦁 ANIMALS',en:'bee',ru:'пчела',pr:'pchela',ex_ru:'Пчела делает мёд.',ex_en:'The bee makes honey.'},
  {id:'x152',cat:'🦁 ANIMALS',en:'squirrel',ru:'белка',pr:'belka',ex_ru:'Белка прыгает по деревьям.',ex_en:'The squirrel jumps between trees.'},
  {id:'x153',cat:'🎓 SCHOOL',en:'school',ru:'школа',pr:'shkola',ex_ru:'Я иду в школу.',ex_en:'I\'m going to school.'},
  {id:'x154',cat:'🎓 SCHOOL',en:'university',ru:'университет',pr:'universitet',ex_ru:'Я учусь в университете.',ex_en:'I study at the university.'},
  {id:'x155',cat:'🎓 SCHOOL',en:'student',ru:'студент',pr:'student',ex_ru:'Я студент первого курса.',ex_en:'I\'m a first-year student.'},
  {id:'x156',cat:'🎓 SCHOOL',en:'teacher',ru:'учитель',pr:'uchitel\'',ex_ru:'Учитель объясняет урок.',ex_en:'The teacher explains the lesson.'},
  {id:'x157',cat:'🎓 SCHOOL',en:'exam',ru:'экзамен',pr:'ekzamen',ex_ru:'Я сдал экзамен!',ex_en:'I passed the exam!'},
  {id:'x158',cat:'🎓 SCHOOL',en:'homework',ru:'домашнее задание',pr:'domashneye zadaniye',ex_ru:'Сделай домашнее задание.',ex_en:'Do your homework.'},
  {id:'x159',cat:'🎓 SCHOOL',en:'to study',ru:'учиться',pr:'uchit\'sya',ex_ru:'Я учусь каждый день.',ex_en:'I study every day.'},
  {id:'x160',cat:'🎓 SCHOOL',en:'to pass an exam',ru:'сдать экзамен',pr:'sdat\' ekzamen',ex_ru:'Надеюсь сдать экзамен.',ex_en:'I hope to pass the exam.'},
  {id:'x161',cat:'🎓 SCHOOL',en:'scholarship',ru:'стипендия',pr:'stipendiya',ex_ru:'Я получаю стипендию.',ex_en:'I receive a scholarship.'},
  {id:'x162',cat:'🎓 SCHOOL',en:'diploma',ru:'диплом',pr:'diplom',ex_ru:'Я получил диплом.',ex_en:'I received my diploma.'},
  {id:'x163',cat:'🎓 SCHOOL',en:'subject',ru:'предмет',pr:'predmet',ex_ru:'Мой любимый предмет — история.',ex_en:'My favorite subject is history.'},
  {id:'x164',cat:'🎓 SCHOOL',en:'math',ru:'математика',pr:'matematika',ex_ru:'Математика — сложный предмет.',ex_en:'Math is a difficult subject.'},
  {id:'x165',cat:'🎓 SCHOOL',en:'break',ru:'перемена',pr:'peremena',ex_ru:'Во время перемены пьём кофе.',ex_en:'We drink coffee during the break.'},
  {id:'x166',cat:'🎵 MUSIC',en:'music',ru:'музыка',pr:'muzyka',ex_ru:'Я люблю слушать музыку.',ex_en:'I love listening to music.'},
  {id:'x167',cat:'🎵 MUSIC',en:'song',ru:'песня',pr:'pesnya',ex_ru:'Это моя любимая песня.',ex_en:'This is my favorite song.'},
  {id:'x168',cat:'🎵 MUSIC',en:'singer',ru:'певец / певица',pr:'pevets / pevitsa',ex_ru:'Она отличная певица.',ex_en:'She\'s an excellent singer.'},
  {id:'x169',cat:'🎵 MUSIC',en:'guitar',ru:'гитара',pr:'gitara',ex_ru:'Я играю на гитаре.',ex_en:'I play guitar.'},
  {id:'x170',cat:'🎵 MUSIC',en:'concert',ru:'концерт',pr:'kontsert',ex_ru:'Мы идём на концерт.',ex_en:'We\'re going to a concert.'},
  {id:'x171',cat:'🎵 MUSIC',en:'to sing',ru:'петь',pr:'pet\'',ex_ru:'Ты умеешь петь?',ex_en:'Can you sing?'},
  {id:'x172',cat:'🎵 MUSIC',en:'to dance',ru:'танцевать',pr:'tantsevat\'',ex_ru:'Она хорошо танцует.',ex_en:'She dances well.'},
  {id:'x173',cat:'🎵 MUSIC',en:'ballet',ru:'балет',pr:'balet',ex_ru:'Русский балет известен во всём мире.',ex_en:'Russian ballet is famous worldwide.'},
  {id:'x174',cat:'🎵 MUSIC',en:'violin',ru:'скрипка',pr:'skripka',ex_ru:'Скрипка звучит волшебно.',ex_en:'The violin sounds magical.'},
  {id:'x175',cat:'🎵 MUSIC',en:'rhythm',ru:'ритм',pr:'ritm',ex_ru:'Чувствуй ритм!',ex_en:'Feel the rhythm!'},
  {id:'x176',cat:'🗺️ DIRECTIONS',en:'left',ru:'налево',pr:'nalevo',ex_ru:'Поверни налево.',ex_en:'Turn left.'},
  {id:'x177',cat:'🗺️ DIRECTIONS',en:'right',ru:'направо',pr:'napravo',ex_ru:'Поверни направо.',ex_en:'Turn right.'},
  {id:'x178',cat:'🗺️ DIRECTIONS',en:'straight ahead',ru:'прямо',pr:'pryamo',ex_ru:'Иди прямо.',ex_en:'Go straight.'},
  {id:'x179',cat:'🗺️ DIRECTIONS',en:'north',ru:'север',pr:'sever',ex_ru:'Едем на север.',ex_en:'We\'re going north.'},
  {id:'x180',cat:'🗺️ DIRECTIONS',en:'south',ru:'юг',pr:'yug',ex_ru:'Он живёт на юге.',ex_en:'He lives in the south.'},
  {id:'x181',cat:'🗺️ DIRECTIONS',en:'far',ru:'далеко',pr:'daleko',ex_ru:'Это далеко отсюда?',ex_en:'Is that far from here?'},
  {id:'x182',cat:'🗺️ DIRECTIONS',en:'close / near',ru:'близко',pr:'blizko',ex_ru:'Это совсем рядом.',ex_en:'It\'s very close.'},
  {id:'x183',cat:'🗺️ DIRECTIONS',en:'How do I get to...?',ru:'Как добраться до...?',pr:'Kak dobrat\'sya do...?',ex_ru:'Как добраться до вокзала?',ex_en:'How do I get to the station?'},
  {id:'x184',cat:'🗺️ DIRECTIONS',en:'map',ru:'карта',pr:'karta',ex_ru:'Покажи мне на карте.',ex_en:'Show me on the map.'},
  {id:'x185',cat:'🗺️ DIRECTIONS',en:'entrance',ru:'вход',pr:'vkhod',ex_ru:'Вход с другой стороны.',ex_en:'The entrance is on the other side.'},
  {id:'x186',cat:'🗺️ DIRECTIONS',en:'exit',ru:'выход',pr:'vykhod',ex_ru:'Где выход?',ex_en:'Where is the exit?'},
  {id:'x187',cat:'🏋️ SPORTS',en:'sport',ru:'спорт',pr:'sport',ex_ru:'Ты занимаешься спортом?',ex_en:'Do you do sports?'},
  {id:'x188',cat:'🏋️ SPORTS',en:'football / soccer',ru:'футбол',pr:'futbol',ex_ru:'Я люблю футбол.',ex_en:'I love football.'},
  {id:'x189',cat:'🏋️ SPORTS',en:'swimming',ru:'плавание',pr:'plavaniye',ex_ru:'Я хожу на плавание.',ex_en:'I go swimming.'},
  {id:'x190',cat:'🏋️ SPORTS',en:'gym',ru:'спортзал',pr:'sportzal',ex_ru:'Я хожу в спортзал три раза в неделю.',ex_en:'I go to the gym three times a week.'},
  {id:'x191',cat:'🏋️ SPORTS',en:'workout',ru:'тренировка',pr:'trenirovka',ex_ru:'Хорошая тренировка!',ex_en:'Good workout!'},
  {id:'x192',cat:'🏋️ SPORTS',en:'to win',ru:'выиграть',pr:'vyigrat\'',ex_ru:'Мы выиграли!',ex_en:'We won!'},
  {id:'x193',cat:'🏋️ SPORTS',en:'to lose',ru:'проиграть',pr:'proigrat\'',ex_ru:'Мы проиграли.',ex_en:'We lost.'},
  {id:'x194',cat:'🏋️ SPORTS',en:'champion',ru:'чемпион',pr:'chempion',ex_ru:'Он чемпион мира.',ex_en:'He\'s world champion.'},
  {id:'x195',cat:'🏋️ SPORTS',en:'yoga',ru:'йога',pr:'yoga',ex_ru:'Йога помогает расслабиться.',ex_en:'Yoga helps to relax.'},
  {id:'x196',cat:'🏋️ SPORTS',en:'chess',ru:'шахматы',pr:'shakhmaty',ex_ru:'Шахматы — игра для умных.',ex_en:'Chess is a game for smart people.'},
  {id:'x197',cat:'🎉 CELEBRATIONS',en:'party',ru:'вечеринка',pr:'vecherinka',ex_ru:'Будет вечеринка в субботу.',ex_en:'There\'ll be a party on Saturday.'},
  {id:'x198',cat:'🎉 CELEBRATIONS',en:'birthday',ru:'день рождения',pr:'den\' rozhdeniya',ex_ru:'Сегодня мой день рождения!',ex_en:'Today is my birthday!'},
  {id:'x199',cat:'🎉 CELEBRATIONS',en:'New Year',ru:'Новый год',pr:'Novyy god',ex_ru:'С Новым годом!',ex_en:'Happy New Year!'},
  {id:'x200',cat:'🎉 CELEBRATIONS',en:'gift / present',ru:'подарок',pr:'podarok',ex_ru:'Какой красивый подарок!',ex_en:'What a beautiful gift!'},
  {id:'x201',cat:'🎉 CELEBRATIONS',en:'toast',ru:'тост',pr:'tost',ex_ru:'Поднимем тост!',ex_en:'Let\'s raise a toast!'},
  {id:'x202',cat:'🎉 CELEBRATIONS',en:'congratulations',ru:'поздравляю',pr:'pozdravlyayu',ex_ru:'Поздравляю с праздником!',ex_en:'Congratulations on the holiday!'},
  {id:'x203',cat:'🎉 CELEBRATIONS',en:'fireworks',ru:'фейерверк',pr:'feyerverk',ex_ru:'Фейерверк был потрясающим.',ex_en:'The fireworks were amazing.'},
  {id:'x204',cat:'🎉 CELEBRATIONS',en:'surprise',ru:'сюрприз',pr:'syurpriz',ex_ru:'Это был приятный сюрприз.',ex_en:'That was a pleasant surprise.'},
  {id:'x205',cat:'🎉 CELEBRATIONS',en:'celebrate',ru:'праздновать',pr:'prazdnovat\'',ex_ru:'Будем праздновать всю ночь!',ex_en:'We\'ll celebrate all night!'},
  {id:'x206',cat:'🔧 HOME LIFE',en:'kitchen',ru:'кухня',pr:'kukhnya',ex_ru:'Я готовлю на кухне.',ex_en:'I\'m cooking in the kitchen.'},
  {id:'x207',cat:'🔧 HOME LIFE',en:'bedroom',ru:'спальня',pr:'spal\'nya',ex_ru:'Спальня — моё любимое место.',ex_en:'The bedroom is my favorite place.'},
  {id:'x208',cat:'🔧 HOME LIFE',en:'bathroom',ru:'ванная',pr:'vannaya',ex_ru:'Ванная занята.',ex_en:'The bathroom is occupied.'},
  {id:'x209',cat:'🔧 HOME LIFE',en:'to clean',ru:'убирать',pr:'ubirat\'',ex_ru:'Надо убрать в квартире.',ex_en:'I need to clean the apartment.'},
  {id:'x210',cat:'🔧 HOME LIFE',en:'to cook',ru:'готовить',pr:'gotovit\'',ex_ru:'Я умею готовить.',ex_en:'I know how to cook.'},
  {id:'x211',cat:'🔧 HOME LIFE',en:'refrigerator',ru:'холодильник',pr:'kholodil\'nik',ex_ru:'В холодильнике ничего нет.',ex_en:'There\'s nothing in the refrigerator.'},
  {id:'x212',cat:'🔧 HOME LIFE',en:'to do laundry',ru:'стирать',pr:'stirat\'',ex_ru:'Я стираю бельё.',ex_en:'I\'m doing the laundry.'},
  {id:'x213',cat:'🔧 HOME LIFE',en:'neighbor',ru:'сосед',pr:'sosed',ex_ru:'Сосед шумит по ночам.',ex_en:'The neighbor is noisy at night.'},
  {id:'x214',cat:'🔧 HOME LIFE',en:'key',ru:'ключ',pr:'klyuch',ex_ru:'Я потерял ключ.',ex_en:'I lost my key.'},
  {id:'x215',cat:'🔧 HOME LIFE',en:'trash / garbage',ru:'мусор',pr:'musor',ex_ru:'Вынеси мусор.',ex_en:'Take out the trash.'},
  {id:'x216',cat:'💡 IDIOMS',en:'grit your teeth',ru:'сжать зубы',pr:'szhat\' zuby',ex_ru:'Пришлось сжать зубы и работать.',ex_en:'Had to grit my teeth and work.'},
  {id:'x217',cat:'💡 IDIOMS',en:'it\'s not the end of the world',ru:'не конец света',pr:'ne konets sveta',ex_ru:'Не конец света, не расстраивайся.',ex_en:'It\'s not the end of the world.'},
  {id:'x218',cat:'💡 IDIOMS',en:'kill two birds with one stone',ru:'убить двух зайцев',pr:'ubit\' dvukh zaytsev',ex_ru:'Убью двух зайцев одним выстрелом.',ex_en:'I\'ll kill two birds with one stone.'},
  {id:'x219',cat:'💡 IDIOMS',en:'every cloud has a silver lining',ru:'нет худа без добра',pr:'net khuda bez dobra',ex_ru:'Нет худа без добра!',ex_en:'Every cloud has a silver lining!'},
  {id:'x220',cat:'💡 IDIOMS',en:'speak of the devil',ru:'лёгок на помине',pr:'lyogok na pomine',ex_ru:'Лёгок на помине!',ex_en:'Speak of the devil!'},
  {id:'x221',cat:'💡 IDIOMS',en:'once in a blue moon',ru:'раз в сто лет',pr:'raz v sto let',ex_ru:'Такое случается раз в сто лет.',ex_en:'That happens once in a blue moon.'},
  {id:'x222',cat:'💡 IDIOMS',en:'better late than never',ru:'лучше поздно, чем никогда',pr:'luchshe pozdno, chem nikogda',ex_ru:'Лучше поздно, чем никогда!',ex_en:'Better late than never!'},
  {id:'x223',cat:'💡 IDIOMS',en:'in seventh heaven',ru:'на седьмом небе',pr:'na sed\'mom nebe',ex_ru:'Я на седьмом небе от счастья.',ex_en:'I\'m in seventh heaven with happiness.'},
  {id:'x224',cat:'💡 IDIOMS',en:'actions speak louder than words',ru:'не словом, а делом',pr:'ne slovom, a delom',ex_ru:'Докажи не словом, а делом.',ex_en:'Prove it with actions, not words.'},
  {id:'x225',cat:'💡 IDIOMS',en:'time heals everything',ru:'время лечит',pr:'vremya lechit',ex_ru:'Не переживай — время лечит.',ex_en:'Don\'t worry — time heals everything.'},
  {id:'x226',cat:'💡 IDIOMS',en:'don\'t burn bridges',ru:'не сжигай мосты',pr:'ne zhigay mosty',ex_ru:'Не стоит сжигать мосты.',ex_en:'You shouldn\'t burn your bridges.'},
  {id:'x227',cat:'💡 IDIOMS',en:'reap what you sow',ru:'что посеешь, то и пожнёшь',pr:'chto poseyesh\', to i pozhnosh\'',ex_ru:'Что посеешь, то и пожнёшь.',ex_en:'You reap what you sow.'},
  {id:'x228',cat:'💡 IDIOMS',en:'friend in need',ru:'друг познаётся в беде',pr:'drug poznayotsya v bede',ex_ru:'Друг познаётся в беде.',ex_en:'A friend in need is a friend indeed.'},
  {id:'x229',cat:'💡 IDIOMS',en:'step by step',ru:'шаг за шагом',pr:'shag za shagom',ex_ru:'Шаг за шагом к цели.',ex_en:'Step by step toward the goal.'},
  {id:'x230',cat:'💡 IDIOMS',en:'don\'t give up',ru:'не сдавайся',pr:'ne sdavaysya',ex_ru:'Не сдавайся, у тебя всё получится.',ex_en:'Don\'t give up, you\'ll succeed.'},
  {id:'x231',cat:'🍺 SOCIAL',en:'let\'s go out',ru:'пойдём куда-нибудь',pr:'poydyom kuda-nibud\'',ex_ru:'Пойдём куда-нибудь вечером.',ex_en:'Let\'s go out tonight.'},
  {id:'x232',cat:'🍺 SOCIAL',en:'bar',ru:'бар',pr:'bar',ex_ru:'Встретимся в баре.',ex_en:'Let\'s meet at the bar.'},
  {id:'x233',cat:'🍺 SOCIAL',en:'I\'m buying',ru:'я угощаю',pr:'ya ugoshchayu',ex_ru:'Сегодня я угощаю!',ex_en:'I\'m buying today!'},
  {id:'x234',cat:'🍺 SOCIAL',en:'your turn',ru:'твоя очередь',pr:'tvoya ochered\'',ex_ru:'Твоя очередь платить.',ex_en:'It\'s your turn to pay.'},
  {id:'x235',cat:'🍺 SOCIAL',en:'hangover',ru:'похмелье',pr:'pokhmel\'ye',ex_ru:'У меня похмелье.',ex_en:'I have a hangover.'},
  {id:'x236',cat:'🍺 SOCIAL',en:'bill / check',ru:'счёт',pr:'schyot',ex_ru:'Принесите счёт, пожалуйста.',ex_en:'Please bring the bill.'},
  {id:'x237',cat:'🍺 SOCIAL',en:'waiter',ru:'официант',pr:'ofitsiant',ex_ru:'Позовём официанта.',ex_en:'Let\'s call the waiter.'},
  {id:'x238',cat:'🍺 SOCIAL',en:'reservation',ru:'бронирование',pr:'bronirovaniye',ex_ru:'У меня есть бронь.',ex_en:'I have a reservation.'},
  {id:'x239',cat:'🍺 SOCIAL',en:'one more round',ru:'ещё по одной',pr:'yeshchyo po odnoy',ex_ru:'Ещё по одной!',ex_en:'One more round!'},
  {id:'x240',cat:'🍺 SOCIAL',en:'to socialize',ru:'общаться',pr:'obshchat\'sya',ex_ru:'Мне нравится общаться с людьми.',ex_en:'I enjoy socializing with people.'},
  {id:'x241',cat:'🏛️ SOCIETY',en:'government',ru:'правительство',pr:'pravitel\'stvo',ex_ru:'Правительство приняло новый закон.',ex_en:'The government passed a new law.'},
  {id:'x242',cat:'🏛️ SOCIETY',en:'law',ru:'закон',pr:'zakon',ex_ru:'Закон — для всех одинаковый.',ex_en:'The law is equal for everyone.'},
  {id:'x243',cat:'🏛️ SOCIETY',en:'rights',ru:'права',pr:'prava',ex_ru:'Я знаю свои права.',ex_en:'I know my rights.'},
  {id:'x244',cat:'🏛️ SOCIETY',en:'election',ru:'выборы',pr:'vybory',ex_ru:'Скоро выборы.',ex_en:'Elections are coming soon.'},
  {id:'x245',cat:'🏛️ SOCIETY',en:'freedom',ru:'свобода',pr:'svoboda',ex_ru:'Свобода — важная ценность.',ex_en:'Freedom is an important value.'},
  {id:'x246',cat:'🏛️ SOCIETY',en:'peace',ru:'мир',pr:'mir',ex_ru:'Мы хотим мира.',ex_en:'We want peace.'},
  {id:'x247',cat:'🏛️ SOCIETY',en:'justice',ru:'справедливость',pr:'spravedlivost\'',ex_ru:'Справедливость должна восторжествовать.',ex_en:'Justice must prevail.'},
  {id:'x248',cat:'🏛️ SOCIETY',en:'equality',ru:'равенство',pr:'ravenstvo',ex_ru:'Равенство — основа демократии.',ex_en:'Equality is the foundation of democracy.'},
  {id:'x249',cat:'🏛️ SOCIETY',en:'news',ru:'новости',pr:'novosti',ex_ru:'Смотрел последние новости?',ex_en:'Did you watch the latest news?'},
  {id:'x250',cat:'🏛️ SOCIETY',en:'society',ru:'общество',pr:'obshchestvo',ex_ru:'Мы живём в современном обществе.',ex_en:'We live in a modern society.'},
  {id:'x251',cat:'✨ WISDOM',en:'life is short',ru:'жизнь коротка',pr:'zhizn\' korotka',ex_ru:'Жизнь коротка — живи полной жизнью.',ex_en:'Life is short — live fully.'},
  {id:'x252',cat:'✨ WISDOM',en:'knowledge is power',ru:'знание — сила',pr:'znaniye — sila',ex_ru:'Знание — сила.',ex_en:'Knowledge is power.'},
  {id:'x253',cat:'✨ WISDOM',en:'patience is gold',ru:'терпение — золото',pr:'terpeniye — zoloto',ex_ru:'Терпение — золото.',ex_en:'Patience is a virtue.'},
  {id:'x254',cat:'✨ WISDOM',en:'live and learn',ru:'век живи, век учись',pr:'vek zhivi, vek uchis\'',ex_ru:'Век живи, век учись.',ex_en:'Live and learn.'},
  {id:'x255',cat:'✨ WISDOM',en:'believe in yourself',ru:'верь в себя',pr:'ver\' v sebya',ex_ru:'Верь в себя и в свои силы.',ex_en:'Believe in yourself and your abilities.'},
  {id:'x256',cat:'✨ WISDOM',en:'never stop growing',ru:'никогда не переставай расти',pr:'nikogda ne perestavay rasti',ex_ru:'Никогда не переставай расти.',ex_en:'Never stop growing.'},
  {id:'x257',cat:'✨ WISDOM',en:'home is best',ru:'в гостях хорошо, а дома лучше',pr:'v gostyakh khorosho, a doma luchshe',ex_ru:'В гостях хорошо, а дома лучше.',ex_en:'There\'s no place like home.'},
  {id:'x258',cat:'✨ WISDOM',en:'the early bird gets the worm',ru:'кто рано встаёт, тому Бог даёт',pr:'kto rano vstayot, tomu Bog dayot',ex_ru:'Кто рано встаёт, тому Бог даёт.',ex_en:'The early bird gets the worm.'},
  {id:'x259',cat:'✨ WISDOM',en:'respect yourself',ru:'уважай себя',pr:'uvazhi sebya',ex_ru:'Уважай себя и других.',ex_en:'Respect yourself and others.'},
  {id:'x260',cat:'✨ WISDOM',en:'everything happens for a reason',ru:'всё не случайно',pr:'vsyo ne sluchayno',ex_ru:'Всё не случайно в этой жизни.',ex_en:'Everything in life happens for a reason.'},
  {id:'x261',cat:'💻 INTERNET',en:'internet',ru:'интернет',pr:'internet',ex_ru:'Есть ли здесь интернет?',ex_en:'Is there internet here?'},
  {id:'x262',cat:'💻 INTERNET',en:'Wi-Fi password',ru:'пароль от вай-фая',pr:'parol\' ot vay-faya',ex_ru:'Какой пароль от вай-фая?',ex_en:'What\'s the Wi-Fi password?'},
  {id:'x263',cat:'💻 INTERNET',en:'social media',ru:'социальные сети',pr:'sotsial\'nyye seti',ex_ru:'Ты есть в социальных сетях?',ex_en:'Are you on social media?'},
  {id:'x264',cat:'💻 INTERNET',en:'to post',ru:'постить',pr:'postit\'',ex_ru:'Я запостил фото.',ex_en:'I posted a photo.'},
  {id:'x265',cat:'💻 INTERNET',en:'to like',ru:'лайкнуть',pr:'layкnut\'',ex_ru:'Лайкни мою фотографию.',ex_en:'Like my photo.'},
  {id:'x266',cat:'💻 INTERNET',en:'to subscribe',ru:'подписаться',pr:'podpisat\'sya',ex_ru:'Подпишись на мой канал.',ex_en:'Subscribe to my channel.'},
  {id:'x267',cat:'💻 INTERNET',en:'comment',ru:'комментарий',pr:'kommentariy',ex_ru:'Оставь комментарий.',ex_en:'Leave a comment.'},
  {id:'x268',cat:'💻 INTERNET',en:'to download',ru:'скачать',pr:'skachat\'',ex_ru:'Скачай это приложение.',ex_en:'Download this app.'},
  {id:'x269',cat:'💻 INTERNET',en:'meme',ru:'мем',pr:'mem',ex_ru:'Это смешной мем.',ex_en:'That\'s a funny meme.'},
  {id:'x270',cat:'💻 INTERNET',en:'to go viral',ru:'стать вирусным',pr:'stat\' virusnym',ex_ru:'Это видео стало вирусным.',ex_en:'This video went viral.'},
  {id:'x271',cat:'🌍 RUSSIAN CULTURE',en:'Russian soul',ru:'русская душа',pr:'russkaya dusha',ex_ru:'Это — настоящая русская душа.',ex_en:'That\'s the true Russian soul.'},
  {id:'x272',cat:'🌍 RUSSIAN CULTURE',en:'dacha',ru:'дача',pr:'dacha',ex_ru:'На выходных едем на дачу.',ex_en:'We\'re going to the dacha on the weekend.'},
  {id:'x273',cat:'🌍 RUSSIAN CULTURE',en:'banya (Russian sauna)',ru:'баня',pr:'banya',ex_ru:'Сходим в баню?',ex_en:'Shall we go to the banya?'},
  {id:'x274',cat:'🌍 RUSSIAN CULTURE',en:'matryoshka',ru:'матрёшка',pr:'matryoshka',ex_ru:'Матрёшка — символ России.',ex_en:'The matryoshka is a symbol of Russia.'},
  {id:'x275',cat:'🌍 RUSSIAN CULTURE',en:'borscht',ru:'борщ',pr:'borshch',ex_ru:'Борщ со сметаной — объедение.',ex_en:'Borscht with sour cream is delicious.'},
  {id:'x276',cat:'🌍 RUSSIAN CULTURE',en:'blini (pancakes)',ru:'блины',pr:'bliny',ex_ru:'Блины на Масленицу!',ex_en:'Blini for Maslenitsa!'},
  {id:'x277',cat:'🌍 RUSSIAN CULTURE',en:'bread and salt',ru:'хлеб и соль',pr:'khleb i sol\'',ex_ru:'Хлеб и соль — знак гостеприимства.',ex_en:'Bread and salt — a sign of hospitality.'},
  {id:'x278',cat:'🌍 RUSSIAN CULTURE',en:'pelmeni',ru:'пельмени',pr:'pel\'meni',ex_ru:'Пельмени со сметаной — вкуснятина.',ex_en:'Pelmeni with sour cream — so tasty.'},
  {id:'x279',cat:'🌍 RUSSIAN CULTURE',en:'kvass',ru:'квас',pr:'kvas',ex_ru:'Квас — традиционный русский напиток.',ex_en:'Kvass is a traditional Russian drink.'},
  {id:'x280',cat:'🌍 RUSSIAN CULTURE',en:'White Nights',ru:'белые ночи',pr:'belye nochi',ex_ru:'В Питере — белые ночи летом.',ex_en:'In St. Petersburg there are White Nights in summer.'},
  {id:'x281',cat:'🌍 RUSSIAN CULTURE',en:'Kremlin',ru:'Кремль',pr:'Kreml\'',ex_ru:'Кремль — сердце Москвы.',ex_en:'The Kremlin is the heart of Moscow.'},
  {id:'x282',cat:'🌍 RUSSIAN CULTURE',en:'Red Square',ru:'Красная площадь',pr:'Krasnaya ploshchad\'',ex_ru:'Красная площадь — главная площадь страны.',ex_en:'Red Square is the main square of the country.'},
  {id:'x283',cat:'🌍 RUSSIAN CULTURE',en:'birch tree',ru:'берёза',pr:'beryoza',ex_ru:'Берёза — символ России.',ex_en:'The birch tree is a symbol of Russia.'},
  {id:'x284',cat:'🔥 STREET TALK',en:'what\'s up?',ru:'как жизнь?',pr:'kak zhizn\'?',ex_ru:'Как жизнь? Что нового?',ex_en:'What\'s up? What\'s new?'},
  {id:'x285',cat:'🔥 STREET TALK',en:'let\'s go! / move!',ru:'погнали!',pr:'pognali!',ex_ru:'Все готовы? Погнали!',ex_en:'Everyone ready? Let\'s go!'},
  {id:'x286',cat:'🔥 STREET TALK',en:'for free',ru:'на халяву',pr:'na khalyavu',ex_ru:'Получил это на халяву.',ex_en:'Got this for free.'},
  {id:'x287',cat:'🔥 STREET TALK',en:'to hustle / grind',ru:'пахать',pr:'pakhat\'',ex_ru:'Я пашу без выходных.',ex_en:'I hustle without days off.'},
  {id:'x288',cat:'🔥 STREET TALK',en:'relax / chill',ru:'расслабься',pr:'rasslab\'sya',ex_ru:'Расслабься, всё под контролем.',ex_en:'Chill, everything\'s under control.'},
  {id:'x289',cat:'🔥 STREET TALK',en:'seriously though',ru:'серьёзно говорю',pr:'seryozno govoryu',ex_ru:'Нет, серьёзно говорю!',ex_en:'No, seriously though!'},
  {id:'x290',cat:'🔥 STREET TALK',en:'insane / crazy good',ru:'безумно',pr:'bezumno',ex_ru:'Это безумно круто!',ex_en:'This is insanely cool!'},
  {id:'x291',cat:'🔥 STREET TALK',en:'in a snap',ru:'мигом',pr:'migom',ex_ru:'Сделаю это мигом.',ex_en:'I\'ll do it in a snap.'},
  {id:'x292',cat:'🔥 STREET TALK',en:'piece of cake',ru:'раз плюнуть',pr:'raz plyunut\'',ex_ru:'Это — раз плюнуть.',ex_en:'That\'s a piece of cake.'},
  {id:'x293',cat:'🔥 STREET TALK',en:'I\'m fed up',ru:'мне надоело',pr:'mne nadoyelo',ex_ru:'Мне это надоело.',ex_en:'I\'m fed up with this.'},
  {id:'x294',cat:'🔥 STREET TALK',en:'exactly!',ru:'точно!',pr:'tochno!',ex_ru:'Точно! Ты прав.',ex_en:'Exactly! You\'re right.'},
  {id:'x295',cat:'🔥 STREET TALK',en:'out of nowhere',ru:'ни с того ни с сего',pr:'ni s togo ni s sego',ex_ru:'Он позвонил ни с того ни с сего.',ex_en:'He called out of nowhere.'},
  {id:'x296',cat:'🔥 STREET TALK',en:'in a great mood',ru:'в отличном настроении',pr:'v otlichnom nastroenii',ex_ru:'Я сегодня в отличном настроении.',ex_en:'I\'m in a great mood today.'},
  {id:'x297',cat:'🔥 STREET TALK',en:'nonstop',ru:'без остановки',pr:'bez ostanovki',ex_ru:'Он говорит без остановки.',ex_en:'He talks nonstop.'},
  {id:'x298',cat:'🔥 STREET TALK',en:'I couldn\'t care less',ru:'мне всё равно',pr:'mne vsyo ravno',ex_ru:'Мне всё равно что они думают.',ex_en:'I couldn\'t care less.'},
  {id:'x299',cat:'🔥 STREET TALK',en:'to brag',ru:'хвастаться',pr:'khvastat\'sya',ex_ru:'Хватит хвастаться!',ex_en:'Stop bragging!'},
  {id:'x300',cat:'🔥 STREET TALK',en:'stop talking nonsense',ru:'не неси чушь',pr:'ne nesti chush\'',ex_ru:'Не неси чушь!',ex_en:'Don\'t talk nonsense!'},
  {id:'x301',cat:'🧘 WELLBEING',en:'health',ru:'здоровье',pr:'zdorov\'ye',ex_ru:'Здоровье — самое главное.',ex_en:'Health is the most important thing.'},
  {id:'x302',cat:'🧘 WELLBEING',en:'mental health',ru:'психическое здоровье',pr:'psikhicheskoye zdorov\'ye',ex_ru:'Психическое здоровье так же важно.',ex_en:'Mental health is just as important.'},
  {id:'x303',cat:'🧘 WELLBEING',en:'stress',ru:'стресс',pr:'stress',ex_ru:'Я испытываю сильный стресс.',ex_en:'I\'m experiencing a lot of stress.'},
  {id:'x304',cat:'🧘 WELLBEING',en:'to relax',ru:'расслабиться',pr:'rasslabit\'sya',ex_ru:'Мне нужно расслабиться.',ex_en:'I need to relax.'},
  {id:'x305',cat:'🧘 WELLBEING',en:'meditation',ru:'медитация',pr:'meditatsiya',ex_ru:'Медитация помогает при стрессе.',ex_en:'Meditation helps with stress.'},
  {id:'x306',cat:'🧘 WELLBEING',en:'good sleep',ru:'хороший сон',pr:'khoroshiy son',ex_ru:'Хороший сон очень важен.',ex_en:'Good sleep is very important.'},
  {id:'x307',cat:'🧘 WELLBEING',en:'tired',ru:'уставший',pr:'ustavshiy',ex_ru:'Я очень устал сегодня.',ex_en:'I\'m very tired today.'},
  {id:'x308',cat:'🧘 WELLBEING',en:'energy',ru:'энергия',pr:'energiya',ex_ru:'У меня нет энергии.',ex_en:'I have no energy.'},
  {id:'x309',cat:'🧘 WELLBEING',en:'breathe deeply',ru:'дыши глубоко',pr:'dyshi gluboko',ex_ru:'Дыши глубоко и спокойно.',ex_en:'Breathe deeply and calmly.'},
  {id:'x310',cat:'🧘 WELLBEING',en:'positive thinking',ru:'позитивное мышление',pr:'pozitivnoye myshleniye',ex_ru:'Позитивное мышление меняет жизнь.',ex_en:'Positive thinking changes your life.'},
  {id:'x311',cat:'🧘 WELLBEING',en:'anxiety',ru:'тревога',pr:'trevoga',ex_ru:'У меня много тревоги.',ex_en:'I have a lot of anxiety.'},
  {id:'x312',cat:'🧘 WELLBEING',en:'inner peace',ru:'душевный покой',pr:'dushevnyy pokoy',ex_ru:'Ищу душевный покой.',ex_en:'I\'m seeking inner peace.'},
  {id:'x313',cat:'🧘 WELLBEING',en:'gratitude',ru:'благодарность',pr:'blagodarnost\'',ex_ru:'Я благодарен за всё.',ex_en:'I\'m grateful for everything.'},
  {id:'x314',cat:'🧘 WELLBEING',en:'self-care',ru:'забота о себе',pr:'zabota o sebe',ex_ru:'Не забывай о заботе о себе.',ex_en:'Don\'t forget about self-care.'},
  {id:'x315',cat:'🧘 WELLBEING',en:'strength',ru:'сила',pr:'sila',ex_ru:'У тебя есть внутренняя сила.',ex_en:'You have inner strength.'},
  {id:'x316',cat:'🧘 WELLBEING',en:'to grow',ru:'расти',pr:'rasti',ex_ru:'Важно расти каждый день.',ex_en:'It\'s important to grow every day.'},
  {id:'x317',cat:'🧘 WELLBEING',en:'to overcome',ru:'преодолеть',pr:'preodolet\'',ex_ru:'Ты сможешь это преодолеть.',ex_en:'You\'ll be able to overcome this.'},
  {id:'x318',cat:'🧘 WELLBEING',en:'balance',ru:'баланс',pr:'balans',ex_ru:'Нужен баланс в жизни.',ex_en:'Balance is needed in life.'},
];
